library:
  join: knockback.js
  compress: true
  files:
    - src/knockback_core.coffee
    - src/knockback_utils.coffee
    - src/knockback_ref_countable.coffee
    - src/knockback_store.coffee
    - src/knockback_collection_observable.coffee
    - src/knockback_default_wrapper.coffee
    - src/knockback_formatted_observable.coffee
    - src/knockback_localized_observable.coffee
    - src/knockback_observable.coffee
    - src/knockback_observables.coffee
    - src/knockback_triggered_observable.coffee
    - src/knockback_attribute_connectors.coffee
    - src/knockback_view_model.coffee

_examples:
  join: _examples.js
  output: test/_examples/build
  files:
    - test/_examples/contact.coffee
    - test/_examples/locale_manager.coffee
    - test/_examples/localized_observables.coffee
    - test/_examples/localized_string.coffee

tests:
  output: build
  directories:
    - test/knockback_legacy
    - test/knockback_utils
    - test/backbone_modelref
    - test/backbone_relational
    - test/knockback_collection_observable
    - test/knockback_formatted_observable
    - test/knockback_localized_observable
    - test/knockback_observable
    - test/knockback_observables
    - test/knockback_triggered_observable
    - test/knockback_view_model
    - test/knockback_memory_management
    - test/packaging
  modes:
    build:
      bundles:
        test/packaging/build/bundle-latest.js:
          underscore: underscore
          backbone: backbone
          backbone-modelref: backbone-modelref
          knockout: vendor/knockout-latest.js
          knockback: knockback.js
          knockback-examples: test/_examples/build/_examples.js
      no_files_ok: ['test/packaging']
    test:
      command: phantomjs
      runner: phantomjs-qunit-runner.js
      files:
        - '**/*.html'

postinstall:
  commands:
    - 'cp underscore vendor/underscore-latest.js'
    - 'cp backbone vendor/backbone-latest.js'
    - 'cp backbone-modelref vendor/backbone-modelref-latest.js'

  # npm version of backbone_relational too old
  # copy_latest_backbone_relational:
  #   command: 'cp'
  #   args: ['backbone-relational', 'vendor/backbone-relational-latest.js']

  # npm version of knockout is not a general-purpose library
  # copy_latest_knockout:
  #   command: 'cp'
  #   args: ['knockout', 'vendor/knockout-latest.js']