gzip_assets: off
compress_assets: off

javascripts:
  'knockback':
    - build/knockback_core.js
    - build/knockback_collection_observable.js
    - build/knockback_localized_observable.js
    - build/knockback_observable.js
    - build/knockback_observables.js
    - build/knockback_triggered_observable.js
    - build/knockback_view_model.js
