test_dirs: [
  'test/knockback_legacy',
  'test/knockback_utils',
  'test/knockback_packaging',
  'test/backbone_modelref',
  'test/backbone_relational',
  'test/knockback_collection_observable',
  'test/knockback_formatted_observable',
  'test/knockback_localized_observable',
  'test/knockback_observable',
  'test/knockback_observables',
  'test/knockback_triggered_observable',
  'test/knockback_view_model',
  'test/knockback_view_model_min',
  'test/knockback_memory_management'
]